// 2017_conflict.res - created by twitch in cooperation with your mom
// .res entries (51):
halflife.wad
liquids.wad
gfx/env/skylineup.tga
gfx/env/skylinedn.tga
gfx/env/skylinelf.tga
gfx/env/skylinert.tga
gfx/env/skylineft.tga
gfx/env/skylinebk.tga
sound/ambience/wind1.wav
sound/weapons/mortarhit.wav
sound/ambience/alien_cycletone.wav
sound/ambience/labdrone1.wav
sound/ambience/alien_powernode.wav
sound/ambience/techamb1.wav
sound/ambience/alienwind2.wav
sound/ambience/alien_purrmachine.wav
sound/ambience/industrial1.wav
sound/ambience/siren.wav
sound/ambience/jetflyby1.wav
sound/vox/adios.wav
sound/vox/amigo.wav
sound/debris/beamstart11.wav
sound/weapons/electro5.wav
sound/vox/bloop.wav
sound/ambience/xtal_down1.wav
sound/debris/beamstart1.wav
sound/ambience/labdrone2.wav
sound/ambience/computalk1.wav
sound/ambience/steamjet1.wav
sprites/b-tele1.spr
sprites/xsmoke1.spr
sprites/enter1.spr
models/teleporter_blue_sprites.mdl
sprites/2017_conflict/b_teleball.spr
sound/2017_conflict/wolfhowl01.wav
sound/2017_conflict/haha2.wav
sound/2017_conflict/corridor_water.wav
sound/2017_conflict/alarm001.wav
sound/2017_conflict/hole_amb3.wav
sound/2017_conflict/allyourbase.wav
sound/2017_conflict/metallica.wav
sound/2017_conflict/scream03.wav
sound/2017_conflict/ghost.wav
sound/2017_conflict/alarm4.wav
sound/2017_conflict/intergalactic.wav
sound/2017_conflict/computalk2_hq.wav
sound/2017_conflict/nuke_explode.wav
sound/2017_conflict/g7_goose3_down.wav
sound/2017_conflict/daffy06.wav
sound/2017_conflict/na.wav
sound/2017_conflict/pusher.wav
sound/2017_conflict/goodbye.wav
sound/2017_conflict/hampton.wav
sound/2017_conflict/dude.wav
sound/2017_conflict/harp.wav
maps/2017_conflict2.txt
maps/2017_conflict2.res



